[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-Clink-arg=-Trpi4.ld",
    "-Crelocation-model=pic",
    "-Clink-arg=-pie"
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
