[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Trpi4.ld"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
